name: shelf_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  postgres: ^3.0.8
  get_it: ^7.6.7
  nanoid2: ^2.0.1

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
